INSERT INTO `course` (`courseName`, `targetGroup`, `area`, `trainerName`) VALUES
('wrestling', 'men', 'martialArts', 'klopp'),
('waterball','men', 'watersport', 'klopp'),
('running', 'men', 'fitness', NULL),
('jogging', 'fam', 'fitness', 'lena'),
('fitnessKids', 'kid', 'fitness', 'klopp'),
('high jump',  'fam', 'athletics', 'lena'),
('obstacle race', 'fam', 'athletics', 'lena'),
('swimming', 'fam', 'watersport', NULL),
('free style', 'kid', 'watersport', 'lazy'),
('aerobics', 'fam', 'fitness', 'lena');

-- --------------------------------------------------------
INSERT INTO `enrollment` (`memName`, `courseID`) VALUES
('hope', 1),
('hope', 5),
('hope', 6),
('hope', 7),
('hope', 10),
('lion', 1),
('lion', 4),
('lion', 5),
('lion', 6),
('lion', 7),
('lion', 10),
('lisa', 6),
('lisa', 9),
('nelly', 1),
('nelly', 4),
('nelly', 5),
('nelly', 6),
('nelly', 7),
('nelly', 10),
('robin', 1),
('robin', 4),
('robin', 5),
('robin', 6),
('robin', 7),
('robin', 10),
('rose', 4),
('rose', 5),
('rose', 6),
('rose', 7),
('rose', 10),
('val', 1),
('val', 4),
('val', 5),
('val', 6),
('valerie', 1),
('valerie', 4),
('valerie', 5),
('valerie', 6),
('valerie', 7),
('valerie', 10);
